sudo: required

services:
  - docker

env:
  global:
    - PACKAGE="apache-tomcat"
    - VERSION="7.0.79"
    - RELEASE="1.el7"
    - DIR="/data"
    - CONTAINER="centos:7"
    
install:
# Build the RPM(s).
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/scripts/build.sh -p ${PACKAGE} -v ${VERSION} -r ${RELEASE}

# Test the installation of the RPM.
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/scripts/test.sh -d ${DIR} -p ${PACKAGE} -v ${VERSION} -r ${RELEASE}

# Create repositorymetadata. (Can be used to publish to i.e. Amazon S3)
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/scripts/createrepo.sh

deploy:
  provider: s3
  access_key_id: "${S3KEY}
  secret_access_key: "${S3SECRET}"
  bucket: "apache-tomcat7.el7"
  region: "eu-west-1"
  skip_cleanup: true
  local_dir: /data/repository

notifications:
  email: false
