sudo: required

services:
  - docker

env:
  global:
    - PACKAGE="apache-tomcat"
    - VERSION="7.0.65"
    - RELEASE="1"
    - DIST="el7"

script:
# Prepare the SPEC file with the correct version information.
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/prepare.sh -p ${PACKAGE} -v ${VERSION} -r ${RELEASE} -d ${DIST}
# Build the RPM(s).
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/build.sh -d /data -s ${PACKAGE}.spec -v ${VERSION}
# Test the installation of the RPM.
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/test.sh
# Publish the RPM.
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/publish.sh -u ${URL} -p /data/rpmbuild/RPMS/x86_64/${PACKAGE}-${VERSION}-1.el7.x86_64.rpm
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/publish.sh -u ${URL} -p /data/rpmbuild/RPMS/noarch/${PACKAGE}-manager-${VERSION}-1.el7.noarch.rpm
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/publish.sh -u ${URL} -p /data/rpmbuild/RPMS/noarch/${PACKAGE}-ROOT-${VERSION}-1.el7.noarch.rpm
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/publish.sh -u ${URL} -p /data/rpmbuild/RPMS/noarch/${PACKAGE}-docs-${VERSION}-1.el7.noarch.rpm
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/publish.sh -u ${URL} -p /data/rpmbuild/RPMS/noarch/${PACKAGE}-examples-${VERSION}-1.el7.noarch.rpm
- docker run -v $(pwd):/data robertdebock/docker-centos7 /bin/sh /data/publish.sh -u ${URL} -p /data/rpmbuild/RPMS/noarch/${PACKAGE}-host-manager-${VERSION}-1.el7.noarch.rpm

notifications:
  email: false
