sudo: required

services:
  - docker

script:
- docker run -v $(pwd):/data robertdebock/docker-centos-rpmbuild /bin/sh /data/rpmbuild.sh -d /data -s apache-tomcat.spec
- ls -l $(pwd)/rpmbuild/RPMS/x86_64/
- ls -l $(pwd)/rpmbuild/RPMS/noarch/

notifications:
  email: false
