sudo: required

services:
  - docker

script:
# Build the RPM(s).
- docker run -v $(pwd):/data robertdebock/docker-centos-rpmbuild /bin/sh /data/build.sh -d /data -s apache-tomcat.spec
# Test the installation of the RPM.
- docker run -v $(pwd):/data robertdebock/docker-centos /bin/sh /data/test.sh

notifications:
  email: false
