sudo: required

services:
  - docker

env:
  global:
    - PACKAGE="apache-tomcat"
    - VERSION="7.0.65"
    - RELEASE="1"
    - DIST="el7"
    - DIR="/data"
    - CONTAINER="centos:7"
    
script:
# Build the RPM(s).
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/buils.sh -p ${PACKAGE} -v ${VERSION} -r ${RELEASE} -d ${DIST}
# Test the installation of the RPM.
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/test.sh -p ${PACKAGE} -v ${VERSION} -r ${RELEASE} -d ${DIST}
# Publish the RPM. The $URL variable is stored in Travis-CI. (it's private...)
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/publish.sh -u ${URL} -p ${DIR}/rpmbuild/RPMS/x86_64/${PACKAGE}-${VERSION}-${RELEASE}.${DIST}.x86_64.rpm
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/publish.sh -u ${URL} -p ${DIR}/rpmbuild/RPMS/noarch/${PACKAGE}-manager-${VERSION}-${RELEASE}.${DIST}.noarch.rpm
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/publish.sh -u ${URL} -p ${DIR}/rpmbuild/RPMS/noarch/${PACKAGE}-ROOT-${VERSION}-${RELEASE}.${DIST}.noarch.rpm
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/publish.sh -u ${URL} -p ${DIR}/rpmbuild/RPMS/noarch/${PACKAGE}-docs-${VERSION}-${RELEASE}.${DIST}.noarch.rpm
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/publish.sh -u ${URL} -p ${DIR}/rpmbuild/RPMS/noarch/${PACKAGE}-examples-${VERSION}-${RELEASE}.${DIST}.noarch.rpm
- docker run -v $(pwd):${DIR} ${CONTAINER} /bin/sh ${DIR}/publish.sh -u ${URL} -p ${DIR}/rpmbuild/RPMS/noarch/${PACKAGE}-host-manager-${VERSION}-${RELEASE}.${DIST}.noarch.rpm

notifications:
  email: false
